public class HospitalManagementGUI extends javax.swing.JFrame {
   
    /**
     * Creates new form HospitalManagementGUI
     */
    public HospitalManagementGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addPatientButton = new javax.swing.JButton();
        dashBoardLabel = new javax.swing.JLabel();
        deleteDoctorButton = new javax.swing.JButton();
        addDoctorButton = new javax.swing.JButton();
        bookAppointmentButton = new javax.swing.JButton();
        viewDoctorsButton = new javax.swing.JButton();
        viewPatientsButton = new javax.swing.JButton();
        editAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addPatientButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addPatientButton.setText("Add Patient");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        dashBoardLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashBoardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashBoardLabel.setText("HOSPITAL MANAGEMENT SYSTEM");

        deleteDoctorButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteDoctorButton.setText("Delete Doctor");
        deleteDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoctorButtonActionPerformed(evt);
            }
        });

        addDoctorButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addDoctorButton.setText("Add Doctor");
        addDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButtonActionPerformed(evt);
            }
        });

        bookAppointmentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookAppointmentButton.setText("Book Appointment");
        bookAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentButtonActionPerformed(evt);
            }
        });

        viewDoctorsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewDoctorsButton.setText("View Doctors");
        viewDoctorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorsButtonActionPerformed(evt);
            }
        });

        viewPatientsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewPatientsButton.setText("View Patients");
        viewPatientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientsButtonActionPerformed(evt);
            }
        });

        editAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editAdminButton.setText("Edit Admin");
        editAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editAdminButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dashBoardLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addPatientButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewPatientsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addComponent(bookAppointmentButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addDoctorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteDoctorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(viewDoctorsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashBoardLabel)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientButton)
                    .addComponent(addDoctorButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDoctorButton)
                    .addComponent(viewPatientsButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDoctorsButton)
                    .addComponent(bookAppointmentButton))
                .addGap(35, 35, 35)
                .addComponent(editAdminButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        AddPatientForm addPatientForm = new AddPatientForm();
        addPatientForm.setVisible(true);
    }                                                

    private void deleteDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        DeleteDoctorForm deleteDoctorForm = new DeleteDoctorForm();
        deleteDoctorForm.setVisible(true);
    }                                                  

    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        AddDoctorForm addDoctorForm = new AddDoctorForm();
        addDoctorForm.setVisible(true);
    }                                               

    private void bookAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        BookAppointmentForm bookAppointmentForm = new BookAppointmentForm();
        bookAppointmentForm.setVisible(true);
    }                                                     

    private void viewDoctorsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        ViewDoctorsForm viewDoctorsForm = new ViewDoctorsForm();
        viewDoctorsForm.setVisible(true);
    }                                                 

    private void viewPatientsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
         ViewPatientsForm viewPatientsForm = new ViewPatientsForm();
         viewPatientsForm.setVisible(true);
       
    }                                                  

    private void editAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String loggedInUsername = "currentUser";
        EditAdminForm editAdminForm = new EditAdminForm(loggedInUsername);
        editAdminForm.setVisible(true);
    }                                               

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalManagementGUI().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JButton addPatientButton;
    private javax.swing.JButton bookAppointmentButton;
    private javax.swing.JLabel dashBoardLabel;
    private javax.swing.JButton deleteDoctorButton;
    private javax.swing.JButton editAdminButton;
    private javax.swing.JButton viewDoctorsButton;
    private javax.swing.JButton viewPatientsButton;
    // End of variables declaration                   
}
